<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/* @var $block \Magento\Framework\View\Element\Template */
?>
<div class="block block-influencer" data-bind="scope: 'influencerProducts'" data-role="influencer-products-sidebar">
    <div class="block-title">
        <strong id="block-influencer-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Favourite Products')) ?></strong>
        <span class="counter qty no-display" data-bind="text: influencerProducts().countCaption, css: {'no-display': !influencerProducts().count}"></span>
    </div>
</div>
